plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/exec"
  - "@semantic-release/github"
  - "@semantic-release/git"
tagFormat:
  - ${version}
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - master
  - next
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
exec:
  - prepareCmd: "npm run build"
  - publishCmd: "npm publish --dry-run"
  - successCmd: "echo 'Release succeeded!'"


